---
services:
  ts-mealie:
    image: tailscale/tailscale:latest
    container_name: "${STACK_PREFIX:-mealie1}-tailscale"
    hostname: "${STACK_PREFIX:-mealie1}-ts"
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TS_EXTRA_ARGS=${TS_EXTRA_ARGS:---advertise-tags=tag:container --reset}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=${TS_USERSPACE:-false}
    volumes:
      - ts_state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    networks:
      - app_net

  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: "${STACK_PREFIX:-mealie1}-app"
    depends_on:
      - ts-mealie
    ports:
      - "${PUBLIC_PORT:-9926}:9000"
    volumes:
      - mealie_data:/app/data
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TIMEZONE:-Canada/Eastern}
      - ALLOW_SIGNUP=${ALLOW_SIGNUP:-true}
      - BASE_URL=${BASE_URL:-http://localhost:${PUBLIC_PORT:-9926}}
    restart: unless-stopped
    networks:
      - app_net

# Static keys; unique *actual* names via `name:` with STACK_PREFIX
volumes:
  mealie_data:
    name: "${STACK_PREFIX:-mealie1}_mealie_data"
  ts_state:
    name: "${STACK_PREFIX:-mealie1}_ts_state"

networks:
  app_net:
    name: "${STACK_PREFIX:-mealie1}_net"

