services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie-app
    restart: always
    ports:
      - "${PUBLIC_PORT:-9926}:9000"
    volumes:
      - mealie-data:/app/data/
    environment:
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE:-Canada/Eastern}

  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - tailscale-data:/var/lib/tailscale
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_HOSTNAME=${TS_HOSTNAME:-mealie-tailscale}
    command: tailscaled

volumes:
  mealie-data:
  tailscale-data:
