services:
  mealie-app:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie-app
    restart: always
    ports:
      - "${PUBLIC_PORT:-9926}:9000"
    volumes:
      - mealie-data:/app/data/
    environment:
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE:-Canada/Eastern}
    networks:
      - internal

  mealie-tailscale:
    image: tailscale/tailscale:latest
    container_name: mealie-tailscale
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: bridge
    volumes:
      - tailscale-data:/var/lib/tailscale
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_HOSTNAME=${TS_HOSTNAME:-mealie-tailscale}
    command: tailscaled
    networks:
      - internal
    depends_on:
      - mealie-app

volumes:
  mealie-data:
  tailscale-data:

networks:
  internal:
    driver: bridge
